# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-25 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191025_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='users',
        ),
    ]
