# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191025_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='message_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
